spring:
  application:
    name: poe
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/poe?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.generate_statistics: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
application:
  security:
    tokenExpirationTime: 15
    refreshTokenExpTime: 60
    tokenIssuer: http://poe.com.br
    tokenSigningKey: xpto #todo: define token as env variable
  cryptContent:
    salt: xpto #todo: provide salt as env variable
    aesKeyIv: xpto #todo: provide 16 bytes key as env variable